package view;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.ColorUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import util.Icones;
import localclasses.Main;
import util.Cards;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Caio
 */
public class Game extends javax.swing.JFrame {
    String myname,  oponentName;
    Icones icon = new Icones();
    Main main = new Main(this);
    Cards CARDS = new Cards(90,120);
    int c1,c2;
    private boolean selectCard= false;
    private boolean loginOk= false;
    /**
     * Creates new form game
     */
    public Game()throws HeadlessException  {
         setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
         
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                handleClosing();
            }
        });
         
        initComponents();
        this.setTitle("Poker");
        startPanels();
    }

    public void startPanels() {
        CardsConnectPanel.setIcon(icon.CARDS_CONNECT);
        coin1.setIcon(icon.COINS);
        coin2.setIcon(icon.COINS);
        coin3.setIcon(icon.COINS);
        coin4.setIcon(icon.COINS);
        user.setIcon(icon.User);
        card1Name.setIcon(icon.CARD1_NAME);
        card2Name.setIcon(icon.CARD2_NAME);
        jLabel8.setIcon(CARDS.getCard(52));
        jLabel19.setIcon(CARDS.getCard(54));
        ConnectPanel.setVisible(true);
        NamePanel.setVisible(false);
        OponentPanel.setVisible(false);
        WaitPanel.setVisible(false);
        GamePanel.setVisible(false);
        EndPanel.setVisible(false);
        HelpPanel.setVisible(false);
    }
   
     private void handleClosing() {
        if(loginOk){
          main.logout();   
        }
        
         dispose();
             
    }
     
    
 
  
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        ConnectPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ip = new javax.swing.JTextField();
        Conectar = new javax.swing.JButton();
        CardsConnectPanel = new javax.swing.JLabel();
        NamePanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        GoButton = new javax.swing.JButton();
        card1Name = new javax.swing.JLabel();
        card2Name = new javax.swing.JLabel();
        OponentPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        AskButton = new javax.swing.JButton();
        helpButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePlayers = new javax.swing.JTable();
        respostaSol = new javax.swing.JLabel();
        WaitPanel = new javax.swing.JPanel();
        timer = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        wMyName = new javax.swing.JLabel();
        wNameOp = new javax.swing.JLabel();
        GamePanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        setPlace2 = new javax.swing.JLabel();
        BankPlayer2 = new javax.swing.JLabel();
        card1 = new javax.swing.JLabel();
        card2 = new javax.swing.JLabel();
        nameOponent = new javax.swing.JLabel();
        coin1 = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        MensagensLabel = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        BankPlayer1 = new javax.swing.JLabel();
        setPlace = new javax.swing.JLabel();
        firstPlace = new javax.swing.JLabel();
        secondPlace = new javax.swing.JLabel();
        coin2 = new javax.swing.JLabel();
        EndPanel = new javax.swing.JPanel();
        eLabelPoints1 = new javax.swing.JLabel();
        eLabelPoints2 = new javax.swing.JLabel();
        ButtonContinue = new javax.swing.JButton();
        ButtonSair = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        eMyName = new javax.swing.JLabel();
        eNameOp = new javax.swing.JLabel();
        ResultGame = new javax.swing.JLabel();
        coin3 = new javax.swing.JLabel();
        coin4 = new javax.swing.JLabel();
        HelpPanel = new javax.swing.JPanel();
        helpbackButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));
        jLayeredPane1.setMaximumSize(new java.awt.Dimension(700, 670));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(700, 670));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(700, 650));

        ConnectPanel.setBackground(new java.awt.Color(255, 255, 255));
        ConnectPanel.setMaximumSize(new java.awt.Dimension(700, 670));
        ConnectPanel.setMinimumSize(new java.awt.Dimension(700, 670));

        jPanel5.setBackground(new java.awt.Color(238, 255, 238));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("IP do Servidor");

        ip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ip.setText("localhost");

        Conectar.setBackground(new java.awt.Color(255, 255, 255));
        Conectar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Conectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/networking1.png"))); // NOI18N
        Conectar.setText("Conectar");
        Conectar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        Conectar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Conectar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConectarMouseEntered1(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited1(evt);
            }
        });
        Conectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Conectar)
                .addGap(21, 21, 21))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ip, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Conectar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout ConnectPanelLayout = new javax.swing.GroupLayout(ConnectPanel);
        ConnectPanel.setLayout(ConnectPanelLayout);
        ConnectPanelLayout.setHorizontalGroup(
            ConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ConnectPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(CardsConnectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ConnectPanelLayout.setVerticalGroup(
            ConnectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConnectPanelLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(CardsConnectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        NamePanel.setBackground(new java.awt.Color(255, 255, 255));
        NamePanel.setMaximumSize(new java.awt.Dimension(700, 670));
        NamePanel.setMinimumSize(new java.awt.Dimension(700, 670));
        NamePanel.setPreferredSize(new java.awt.Dimension(700, 670));

        jPanel6.setBackground(new java.awt.Color(238, 255, 238));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Digite seu apelido:");

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        GoButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/right-arrow1.png"))); // NOI18N
        GoButton.setText("Avançar");
        GoButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        GoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(284, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout NamePanelLayout = new javax.swing.GroupLayout(NamePanel);
        NamePanel.setLayout(NamePanelLayout);
        NamePanelLayout.setHorizontalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NamePanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NamePanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(card1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(card2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        NamePanelLayout.setVerticalGroup(
            NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NamePanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(NamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NamePanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(card1Name, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(100, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NamePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(card2Name, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );

        OponentPanel.setBackground(new java.awt.Color(255, 255, 255));
        OponentPanel.setMaximumSize(new java.awt.Dimension(700, 670));
        OponentPanel.setMinimumSize(new java.awt.Dimension(700, 670));
        OponentPanel.setPreferredSize(new java.awt.Dimension(700, 670));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Selecione o oponente:");

        AskButton.setBackground(new java.awt.Color(255, 255, 255));
        AskButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AskButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/gamer.png"))); // NOI18N
        AskButton.setText("Solicitar partida");
        AskButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        AskButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AskButtonActionPerformed(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/information.png"))); // NOI18N
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(255, 255, 255));
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/rotation.png"))); // NOI18N
        refreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ConectarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jTablePlayers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTablePlayers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTablePlayers);

        respostaSol.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        respostaSol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        respostaSol.setText("Resposta");
        respostaSol.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout OponentPanelLayout = new javax.swing.GroupLayout(OponentPanel);
        OponentPanel.setLayout(OponentPanelLayout);
        OponentPanelLayout.setHorizontalGroup(
            OponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OponentPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(OponentPanelLayout.createSequentialGroup()
                .addGroup(OponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OponentPanelLayout.createSequentialGroup()
                        .addGap(480, 480, 480)
                        .addComponent(refreshButton))
                    .addGroup(OponentPanelLayout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(AskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(OponentPanelLayout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(OponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                            .addComponent(respostaSol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        OponentPanelLayout.setVerticalGroup(
            OponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OponentPanelLayout.createSequentialGroup()
                .addGroup(OponentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(OponentPanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel2))
                    .addGroup(OponentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(helpButton)))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshButton)
                .addGap(5, 5, 5)
                .addComponent(AskButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(respostaSol, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );

        WaitPanel.setBackground(new java.awt.Color(255, 255, 255));
        WaitPanel.setMaximumSize(new java.awt.Dimension(700, 670));
        WaitPanel.setMinimumSize(new java.awt.Dimension(700, 670));

        timer.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        timer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timer.setText("0");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/citizenBig.jpg"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/emperorBig.jpg"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("VS");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("A partida começará em ");

        wMyName.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        wMyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wMyName.setText("MeuNome");

        wNameOp.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        wNameOp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wNameOp.setText("NomeOponente");

        javax.swing.GroupLayout WaitPanelLayout = new javax.swing.GroupLayout(WaitPanel);
        WaitPanel.setLayout(WaitPanelLayout);
        WaitPanelLayout.setHorizontalGroup(
            WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(WaitPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wMyName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wNameOp)
                    .addComponent(jLabel3))
                .addGap(77, 77, 77))
        );
        WaitPanelLayout.setVerticalGroup(
            WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WaitPanelLayout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wMyName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wNameOp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaitPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)))
                    .addGroup(WaitPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addGroup(WaitPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        GamePanel.setBackground(new java.awt.Color(255, 255, 255));
        GamePanel.setMaximumSize(new java.awt.Dimension(700, 670));
        GamePanel.setMinimumSize(new java.awt.Dimension(700, 670));
        GamePanel.setPreferredSize(new java.awt.Dimension(700, 670));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 342));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 342));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 342));

        setPlace2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cardEmpty.png"))); // NOI18N

        BankPlayer2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BankPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BankPlayer2.setText("0");

        card1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/setCard.png"))); // NOI18N

        card2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/setCard.png"))); // NOI18N

        nameOponent.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        nameOponent.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameOponent.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(239, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(setPlace2)
                        .addGap(174, 174, 174)
                        .addComponent(BankPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coin1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(card1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(card2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(nameOponent, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(card1)
                            .addComponent(card2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(setPlace2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameOponent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BankPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(coin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        MensagensLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        MensagensLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MensagensLabel.setText("O jogo começou!!!");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MensagensLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MensagensLabel))
        );

        jPanel3.setBackground(new java.awt.Color(238, 255, 238));

        BankPlayer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BankPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BankPlayer1.setText("0");

        setPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/cardEmpty.png"))); // NOI18N

        firstPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/citizenlow.jpg"))); // NOI18N
        firstPlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstPlaceMouseClicked(evt);
            }
        });

        secondPlace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/citizenlow.jpg"))); // NOI18N
        secondPlace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                secondPlaceMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(firstPlace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(secondPlace)
                        .addGap(269, 269, 269))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(setPlace)
                        .addGap(166, 166, 166)
                        .addComponent(BankPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coin2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setPlace))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(coin2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BankPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstPlace, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(secondPlace, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        EndPanel.setBackground(new java.awt.Color(255, 255, 255));
        EndPanel.setMaximumSize(new java.awt.Dimension(700, 670));
        EndPanel.setMinimumSize(new java.awt.Dimension(700, 670));
        EndPanel.setPreferredSize(new java.awt.Dimension(700, 670));

        eLabelPoints1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eLabelPoints1.setText("0");

        eLabelPoints2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        eLabelPoints2.setText("0");

        ButtonContinue.setBackground(new java.awt.Color(255, 255, 255));
        ButtonContinue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonContinue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/right-arrow1.png"))); // NOI18N
        ButtonContinue.setText("Continuar");
        ButtonContinue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ButtonContinue.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        ButtonContinue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpbackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        ButtonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonContinueActionPerformed(evt);
            }
        });

        ButtonSair.setBackground(new java.awt.Color(255, 255, 255));
        ButtonSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/door.png"))); // NOI18N
        ButtonSair.setText("Sair");
        ButtonSair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ButtonSair.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ButtonSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpbackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        ButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSairActionPerformed(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/citizenBig.jpg"))); // NOI18N

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/emperorBig.jpg"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("VS");

        eMyName.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        eMyName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eMyName.setText("MeuNome");

        eNameOp.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 24)); // NOI18N
        eNameOp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eNameOp.setText("NomeOponente");

        ResultGame.setFont(new java.awt.Font("Lithos Pro Regular", 1, 36)); // NOI18N
        ResultGame.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultGame.setText("RESULTADO");

        javax.swing.GroupLayout EndPanelLayout = new javax.swing.GroupLayout(EndPanel);
        EndPanel.setLayout(EndPanelLayout);
        EndPanelLayout.setHorizontalGroup(
            EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndPanelLayout.createSequentialGroup()
                .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(eLabelPoints1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coin3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eLabelPoints2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(coin4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResultGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNameOp)
                            .addComponent(jLabel10))))
                .addGap(71, 71, 71))
        );
        EndPanelLayout.setVerticalGroup(
            EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EndPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ResultGame, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addComponent(eNameOp, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addComponent(eMyName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EndPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EndPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EndPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coin3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(eLabelPoints1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(eLabelPoints2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EndPanelLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(coin4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(80, 80, 80)
                .addGroup(EndPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        HelpPanel.setBackground(new java.awt.Color(255, 255, 255));
        HelpPanel.setMaximumSize(new java.awt.Dimension(700, 670));
        HelpPanel.setMinimumSize(new java.awt.Dimension(700, 670));
        HelpPanel.setPreferredSize(new java.awt.Dimension(700, 670));

        helpbackButton.setBackground(new java.awt.Color(255, 255, 255));
        helpbackButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        helpbackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/right-arrowreverse.png"))); // NOI18N
        helpbackButton.setText("Voltar");
        helpbackButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        helpbackButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        helpbackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpbackButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ConectarMouseExited(evt);
            }
        });
        helpbackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpbackButtonActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/emperorlow.jpg"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/more.png"))); // NOI18N

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/remove.png"))); // NOI18N

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/citizenlow.jpg"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/right-arrow(2).png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/right-arrow(2).png"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Guia:\n\nOne Card Poker é um jogo jogado com duas\ncartas. \n\nAo iniciar uma partida, cada jogador\nrecebe duas cartas. Preste atenção às \ncartas de seu oponente, elas serão \ncinzas se forem cartas baixas (menores \ndo que 8) ou vermelhas se forem cartas \naltas (maiores do que 7).\nEspada > Copa > Ouro > Paus\nAssim que as cartas são distribuídas\ncomeçam as apostas. Os jogadores fazem\nturnos apostando ate que ambos\nconcordem em um valor. Você pode correr\na qualquer momento, mas cuidado, um\njogador que corre perde todos os pontos\njá apostados.\n\nRealizadas as apostas, basta escolher\n sua carta e esperar. Assim que ambos os\njogadores escolherem, o vencedor recebe \no seu premio e a próxima rodada começa. \n\nO jogo termina quando um jogador estiver\ncom 0 pontos. \n\nBoa sorte.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout HelpPanelLayout = new javax.swing.GroupLayout(HelpPanel);
        HelpPanel.setLayout(HelpPanelLayout);
        HelpPanelLayout.setHorizontalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(helpbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelpPanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );
        HelpPanelLayout.setVerticalGroup(
            HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelpPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelpPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(HelpPanelLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(HelpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)))
                    .addGroup(HelpPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(helpbackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jLayeredPane1.setLayer(ConnectPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(NamePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(OponentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(WaitPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(GamePanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(EndPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(HelpPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OponentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(NamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 22, Short.MAX_VALUE)))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WaitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ConnectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 696, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(OponentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(GamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(EndPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(HelpPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(NamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(WaitPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(ConnectPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, 670, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void connectWithServer() {
//        cliente = new ClienteConnection(this, ip.getText());
//        cliente.iniciar();
    }
    public void newTurn(String msg){
        setLabelMensagem(msg);
         selectCard = false;
         firstPlace.setVisible(true);
         secondPlace.setVisible(true);
    }
    public void setOponentCard(int card){
        setPlace2.setIcon(CARDS.getCard(card));
    }
    public void setFlagCardOne(String flag){
        if(flag == "Alta"){
            card1.setIcon(CARDS.getCard(52));
        }else{
              card1.setIcon(CARDS.getCard(54));
        }
       
    }
    public void setFlagCardTwo(String flag){
        if(flag == "Alta"){
            card2.setIcon(CARDS.getCard(52));
        }else{
             card2.setIcon(CARDS.getCard(54));
        }
    }
    public void setBank(int bank,int oponentBank){
        BankPlayer1.setText(""+bank);
        BankPlayer2.setText(""+oponentBank);
    }
    public void setOponentName(String oponentName){
        this.oponentName = oponentName;
        nameOponent.setText(oponentName);
    }
    public void setLabelMensagem(String msg){
        MensagensLabel.setText(msg);
    }
    public void setLabelEndMensagem(String msg){
        ResultGame.setText(msg);
    }
    public void setCards(int card1, int card2){
          c1 = card1;
      firstPlace.setIcon(CARDS.getCard(card1));
       c2= card2;
       secondPlace.setIcon(CARDS.getCard(card2));
      
    }
   
    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        if (name.getText().length() > 3) {
            myname = name.getText();
            main.setName(name.getText());
            main.iniciar();
            oponentPanelShow();
            loginOk=true;
        } else {
            JOptionPane.showMessageDialog(null, "Digite um nome com pelo menos 4 caracteres");

        }
    }//GEN-LAST:event_GoButtonActionPerformed

    private void challenge(String nomeSolicitado) throws RemoteException {
        respostaSol.setVisible(true);
        respostaSol.setText("Aguarde a resposta");
        if (main.challenge(nomeSolicitado)) {
            GamePanelShow();
            setOponentName(nomeSolicitado);
        } else {
        respostaSol.setText("Seu oponente recusou a partida");
        }
    }

    private void AskButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AskButtonActionPerformed
        DefaultTableModel tableAlergias = (DefaultTableModel) jTablePlayers.getModel();
        if (jTablePlayers.getSelectedRow() >= 0 && !tableAlergias.getValueAt(jTablePlayers.getSelectedRow(), 0).equals(myname)) {
            String nomeSolicitacao = (String) tableAlergias.getValueAt(jTablePlayers.getSelectedRow(), 0);

            try {
        challenge(nomeSolicitacao);
        main.setOponent(nomeSolicitacao);
            } catch (RemoteException ex) {
                Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um oponente para continuar");
        }
    }//GEN-LAST:event_AskButtonActionPerformed

    private void ButtonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonContinueActionPerformed
        retornLobbyPanel();
    }//GEN-LAST:event_ButtonContinueActionPerformed

    private void helpbackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpbackButtonActionPerformed
        HelpPanel.setVisible(false);
        OponentPanel.setVisible(true);
    }//GEN-LAST:event_helpbackButtonActionPerformed

    private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
         HelpPanel.setVisible(true);
        OponentPanel.setVisible(false);
    }//GEN-LAST:event_helpButtonActionPerformed



    private void adicionaNaTabela(ArrayList<ArrayList> users, ArrayList<ArrayList> teste, DefaultTableModel table) {
        for (int j = 0; j < users.size(); j++) {

            table.addRow(new Object[]{users.get(j).get(0), users.get(j).get(1)});

        }
    }

    private void refresh() {
        ArrayList<ArrayList> users;
        try {
            users = main.getPlayers();
            DefaultTableModel tablePlayers = (DefaultTableModel) jTablePlayers.getModel();
            tablePlayers.setNumRows(0);

            adicionaNaTabela(users, users, tablePlayers);

        } catch (RemoteException ex) {
            Logger.getLogger(Game.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        refresh();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void ButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSairActionPerformed
    handleClosing();
        
    }//GEN-LAST:event_ButtonSairActionPerformed

    private void ConectarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarMouseEntered
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.GRAY);
    }//GEN-LAST:event_ConectarMouseEntered

    private void helpbackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpbackButtonMouseEntered
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.GRAY);
    }//GEN-LAST:event_helpbackButtonMouseEntered

    private void ConectarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarMouseExited
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.WHITE);
    }//GEN-LAST:event_ConectarMouseExited

    private void firstPlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstPlaceMouseClicked
        if(!selectCard){
              main.setCardSelected(c1);
        setPlace.setIcon(CARDS.getCard(c1));
        firstPlace.setVisible(false);
        selectCard=true;
        setCardDispose();
        }
    }//GEN-LAST:event_firstPlaceMouseClicked

    private void secondPlaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_secondPlaceMouseClicked
       if(!selectCard){
        main.setCardSelected(c2);
        setPlace.setIcon(CARDS.getCard(c2));
        secondPlace.setVisible(false);
        selectCard=true;
        setCardDispose();
       }
    }//GEN-LAST:event_secondPlaceMouseClicked

    private void ConectarMouseEntered1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarMouseEntered1
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.GRAY);
    }//GEN-LAST:event_ConectarMouseEntered1

    private void ConectarMouseExited1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConectarMouseExited1
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.WHITE);
    }//GEN-LAST:event_ConectarMouseExited1

    private void ConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConectarActionPerformed
        main.setIP(ip.getText());
        ConnectPanel.setVisible(false);
        NamePanel.setVisible(true);
    }//GEN-LAST:event_ConectarActionPerformed
   
    private void setCardDispose(){
        firstPlace.setIcon(CARDS.getCard(53));
        secondPlace.setIcon(CARDS.getCard(53));
    }
    private void oponentPanelShow() {
        NamePanel.setVisible(false);
        OponentPanel.setVisible(true);
    }

    public void GamePanelShow() {
        OponentPanel.setVisible(false);
        GamePanel.setVisible(true);
    }
    public void endGame(String msg){
        if(msg == "Você venceu este jogo."){
            eLabelPoints1.setText("200");
            eLabelPoints2.setText("0");
        }else{
            eLabelPoints1.setText("0");
            eLabelPoints2.setText("200");
            jLabel10.setIcon(icon.SLAVE_BIG);
        }
       eMyName.setText(myname);
       eNameOp.setText(oponentName);
        setLabelEndMensagem(msg);
        endPanel();
        
    }
    public void endPanel(){
          GamePanel.setVisible(false);
          EndPanel.setVisible(true);
    }
    public void retornLobbyPanel(){
        respostaSol.setText("Resposta");
        MensagensLabel.setText("O jogo começou!!!");
        setPlace2.setIcon(icon.CARD_EMPTY);
        setPlace.setIcon(icon.CARD_EMPTY);
        EndPanel.setVisible(false);
          OponentPanel.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AskButton;
    private javax.swing.JLabel BankPlayer1;
    private javax.swing.JLabel BankPlayer2;
    private javax.swing.JButton ButtonContinue;
    private javax.swing.JButton ButtonSair;
    private javax.swing.JLabel CardsConnectPanel;
    private javax.swing.JButton Conectar;
    private javax.swing.JPanel ConnectPanel;
    private javax.swing.JPanel EndPanel;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JButton GoButton;
    private javax.swing.JPanel HelpPanel;
    private javax.swing.JLabel MensagensLabel;
    private javax.swing.JPanel NamePanel;
    private javax.swing.JPanel OponentPanel;
    private javax.swing.JLabel ResultGame;
    private javax.swing.JPanel WaitPanel;
    private javax.swing.JLabel card1;
    private javax.swing.JLabel card1Name;
    private javax.swing.JLabel card2;
    private javax.swing.JLabel card2Name;
    private javax.swing.JLabel coin1;
    private javax.swing.JLabel coin2;
    private javax.swing.JLabel coin3;
    private javax.swing.JLabel coin4;
    private javax.swing.JLabel eLabelPoints1;
    private javax.swing.JLabel eLabelPoints2;
    private javax.swing.JLabel eMyName;
    private javax.swing.JLabel eNameOp;
    private javax.swing.JLabel firstPlace;
    private javax.swing.JButton helpButton;
    private javax.swing.JButton helpbackButton;
    private javax.swing.JTextField ip;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePlayers;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameOponent;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel respostaSol;
    private javax.swing.JLabel secondPlace;
    private javax.swing.JLabel setPlace;
    private javax.swing.JLabel setPlace2;
    private javax.swing.JLabel timer;
    private javax.swing.JLabel user;
    private javax.swing.JLabel wMyName;
    private javax.swing.JLabel wNameOp;
    // End of variables declaration//GEN-END:variables
}
